Testing more than 2 args:
>>> add_integer(1, 2, 3)
Traceback(most recent call last):
...
TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given

Testing complex integer:
>>> add_integer(10+9j)
Traceback(most recent call last):
...
TypeError: a must be an integer